### ISSUE TITLE
Project Mgmt

### ISSUE THREAD

**Issue by brianjmiller** [adlnet/xAPI_LRS_Test#13]
I've been thinking through things a bit with the turn over of the code and the merging of the first big PR and the presence of a new community submitted one, I think a few things need to be considered before too much community effort is put towards coverage/changes.

### Versioning

Right now the suite only really has a "source version" so to speak. In other words the `package.json` file contains a "version" property. That property is intended to indicate the version of the code base that someone may be running at a given point. That is an important version to maintain correctly and is intended to be semver'd since it is part of the npm handling. At any point anyone should be able to see what version of the code they have.

There (likely) needs to exist another version that indicates the "test version" or "conformance version". This is the version of the tests or assertions themselves and should be thought of as separate from the "source version" as described above. The "source" version should be bumped anytime any change to any code/documentation/etc. changes, but this need not cause a bump to the "test version". There are a great deal of changes that could be made to the code base that do not affect whether an LRS will produce a conformant/non-conformant result (the currently open PR, #12, is an example). The "test version" would only get bumped when a test or assertion is added, deleted, or changed such that an LRS may give a different result than on previous runs of the suite. This "test version" is the one that an LRS could report publicly for conformance and an LRS need not run the most recent "source version" of the suite to be considered conformant with a particular "test version".

Assuming the above is both clear and needed then I'd propose a couple of next steps and process for future handling of changes.

### Maintenance

In so far as there probably needs to be a lag between when assertions are pull requested/merged and when they cause a bump to the overall "test version" in order to allow LRSs to catch up and anticipate future conformance issues I would suggest that these types of changes are tracked in a separate branch from other changes to the source.

In order to achieve this the "master" branch would track code changes not affecting the conformance outcome and would bump the version in the package.json file. These can be done rapidly and the version increment continuously following the normal semver rules for software projects. A second "conformance" (better name accepted) branch would be set up for tracking all changes that need to adjust the "test version". These changes would be tracked separately, do not bump the 'package.json' and do not individually bump the "test version". When the test group decides to cut a new release of conformance the 'package.json' would be bumped, the "test version" would be bumped, and this branch would be merged back into "master" as a new conformance release. Any LRS wishing to track their own conformance could pay attention to changes on this branch and make sure that when the release landed they were already conformant. Periodically (potentially after each merge) the "master" branch can be merged into the "conformance" branch so that it keeps up with the coding changes themselves and becomes an easy merge at the "test version" bump release time.

### Next steps

* Add a JSON file for tracking the "test version" outside the 'package.json' and for any other data deemed necessary (I don't know what that'd be but could conceive of it).
* Add an output line in the base grunt processing to indicate the "source version" and "test version" currently being executed, or making this a separate grunt task completely (which would be trivial).
* Come up with good names for "source version" and "test version" (unless those are good enough).
* Create the "conformance branch" (come up with better name if necessary).
* Add a contributing.md doc explaining the rationale above and how developers should approach their changes and pull requests.
* Determine whether ADL has one or more members able to execute on the above strategy and if not determine test group people that can and get them commit access.
* Set out a time table/schedule/road map for expected release cycle of the "test version" bumps. Given the need to quickly ramp up coverage this cycle time should be kept relatively short, but it is necessary for the LRS vendors to be able to anticipate it.

### Note on semver for the source

semver is most often necessary for public APIs that may have compatibility issues. At least so far, the test suite is fairly well contained and is really more of an application than library. To that end I'd propose the only changes that would cause a major number bump would be changes to the command line execution itself or configuration file format changes rather than anything internal to the code, even for changes to the individual library parts, such as the fixtures, or steps, etc. Merges of the "conformance branch" as described above would be minor version bumps (so long as they didn't incompatibly break the CLI/config file) as would additions of tasks, additions to the stages, etc. Nearly anything else could be considered a patch version.

*Please tell me (us) what I've missed in the above, whether it is crazy over management, whether it is a viable process for maintenance, etc.*

**Comment by vbudhram** [comment]
Here is an alternative solution. Would splitting the repository in two help with versioning? One repository would define the tests the run specific to a version of the spec and the other would contain all the test running utilities. Each repository would have there own version number and the test runner repo could have a dependency on the spec repo.

You would be able to specify the version of the spec you would like to run with any version of the test repo.

**Comment by brianjmiller** [comment]
@vbudhram interesting thought. I'm concerned that it will add enough management overhead that it will make things worse rather than better. Dependency management is a tough problem to get a right solution for, I think it might compound the problem since you still have to deal with two versions, but they'd be in separate locations. (Note that this is just $.02, and it'd work if people want to manage it.)

**Comment by brianjmiller** [comment]
I've started work on the programmatic additions to the code to make this happen. I hope to PR tomorrow or Friday, no later than next week's call. I'm also looking at making it easier to report pass/fail for individual sections of the suite and/or the suite overall. If that proves too difficult I'll cut my efforts short with enough to satisfy this issue.

**Comment by ryansmith94** [comment]
Good stuff! Thanks for the update @brianjmiller :+1:

**Comment by brianjmiller** [comment]
Not quite to a PR yet (had a sick day in there) but making progress.

![Uploading Screen Shot 2015-03-11 at 1.23.17 PM.png . . .]()

**Comment by brianjmiller** [comment]
![screen shot 2015-03-11 at 1 23 17 pm](https://cloud.githubusercontent.com/assets/95960/6603740/0874692e-c7f2-11e4-9f16-4296cd3acd16.png)

**Comment by ryansmith94** [comment]
Looks good Brian!

**Comment by brianjmiller** [comment]
Just an update, I'm making progress (a lot more went on behind the scenes then these two images would otherwise suggest).
![screen shot 2015-04-03 at 2 06 17 pm](https://cloud.githubusercontent.com/assets/95960/6987248/ebe8211c-da0a-11e4-9844-c354f15e7b63.png)

**Comment by ryansmith94** [comment]
Looks awesome! :D

**Comment by brianjmiller** [comment]
@ryansmith94 see #41, pointing to you since you've been most engaged to date! 2nd by @vbudhram.

**Comment by ryansmith94** [comment]
Thanks :)

**Comment by brianjmiller** [comment]
Other than the following two points from my original dissertation, everything has now been addressed:

* Determine whether ADL has one or more members able to execute on the above strategy and if not determine test group people that can and get them commit access.
* Set out a time table/schedule/road map for expected release cycle of the "test version" bumps. Given the need to quickly ramp up coverage this cycle time should be kept relatively short, but it is necessary for the LRS vendors to be able to anticipate it.

On point 1, I think we are fine to continue with letting @andyjohnson manage the actual merges, etc. and can always revisit that in a meeting. On point 2, I think it would still be good to have such a schedule but I don't think that is necessary to keep this issue open. The testing group can come to a conclusion on its own, presumably with input from the known significant LRS vendors.

So I'm going to close this issue.
